services:
  server:
    build:
      context: .
      dockerfile: ./BasicAuthAPI/Dockerfile
    restart: always
    
    ports:
      - "3000:8080"
    environment:
      - ConnectionStrings__AppDb=Data Source=./db.sqlite